name: Production deploy
on:
  push:
    branches:
    - 'main'
    paths:
    - 'api/CustomerAPI/**' 
    - '.github/workflows/*' 

jobs:
   deploy_to_prod:
    name: 'Production deployment'
    uses: ./.github/workflows/main.yml         #Call the existing workflow 
    secrets: inherit
    with:
      name: erande2prod
      environment: 'prod'  